### PR TITLE
Added 2 new experiments!

### PR DESCRIPTION
**Pull request by SpoonyBoobah**
Added 2 experiments to StationScience, the first is restoring the old experiment that was originally built into the F-RRY Zoology Bay;

Zoology Observations
Tier 1 - Physiology / Creatures
Requires F-RRY Zoology Bay,
Completes: 25 Bioproducts
How are our cute furry creatures affected by being in space, millions of kilometres from Kerbin? This pod contains a variety of observation and surveillance equipment to analyse how the creatures have changed. You will need a F-RRY Zoology Bay to perform this experiment. Note: don't attach directly to your station, unless you intend to return it to the surface.
Reports: Every planet, moon and 1 each in space and 1 on the surface.

Nutritional Value
Tier 2 - Biology / Plants
Requires TH-NKR Research Lab and F-RRY Zoology Bay
Completes: 75 Eurekas and 25 Bioproducts
How does food grown in space compare to home grown snacks? Lets feed it to some creatures in the Zoo Bay and find out! You will need a TH-NKR Research Lab and F-RRY Zoology Bay for this experiment. Note: don't attach directly to your station, unless you intend to return it to the surface.
Reports: Every planet and moon, only 1 report per SOI.

### CODE REVIEW

**Comment by SpoonyBoobah** [comment]
Just wanted to note also, I did a bit of a messup with github during my dev of this pull... hence the loads of deletions, dont worry I have'nt deleted the whole mod, just I broke it and then copied it back again :D

**Comment by SpoonyBoobah** [comment]
Also for nutritional value I think I set it up correctly so that it will show only the report written per planet/moon and not want like specific reports for InSpace and SrfLanded for example...

**Comment by SpoonyBoobah** [comment]
Heya @linuxgurugamer could you also when creating the new release... copy the .mu file of StnExperiment 5 and use it to overwrite StnExperiment6 with renaming it to 'StnExperiment6', making Kuarq Bio-activity a Blue Pod instead of a purple? Thanks! So now there will be 3 Green, 3 Red, 3 Blue and 0 Purple Pods, they will be coming back later :D

**Comment by linuxgurugamer** [comment]
@SpoonyBoobah This PR is making me nervous.  Could you redo it after recloning the mod?  Also, that comment on May 25 of copying the .mu file, can you incorporate that as well?

Edit:  I made a new copy and saw that the chagnes were only cfg files, and a couple of .mu files (see pic)
WinMergeU_2022-08-13_19-03-37
.

If this is all that's changing, then if you do one more PR with the .mu change mentioned earlier, I can merge it

**Comment by SpoonyBoobah** [comment]
Pod colour swap has been completed... Have pulled the purple pod file out of the directory for future use later...

**Comment by linuxgurugamer** [comment]
@SpoonyBoobah Do you still want me to merge this?  I can ignore the two conflicting files, let me know please

**Comment by SpoonyBoobah** [comment]
> @SpoonyBoobah Do you still want me to merge this? I can ignore the two conflicting files, let me know please

Probably not, am making progress on my branch... just working on models now for the new parts :)

**Comment by linuxgurugamer** [comment]
I'm puzzled, I thought you were doing your own branch.  This PR has a couple of conflicts:

StationScience/obj/Debug/StationScience.csproj.CoreCompileInputs.cache
StationScience/obj/Debug/StationScience.csproj.FileListAbsolute.txt

You really shouldn't include anything in the obj or bin directories in the repo.

**Comment by SpoonyBoobah** [comment]
Apologies,

I am not sure what has happened... I never submitted anything to this pull.
Thats weird....

**Comment by SpoonyBoobah** [comment]
Dont know why this was still opened...

Have now fixed it by closing

**Pull request closed without merging**
