### PR TITLE
Changed Plant to Seeds and added more reports

### PR DESCRIPTION
**Pull request by SpoonyBoobah**
First batch of my reports for Experiment: Plant Growth
Decided to change 'Plant' to 'Seeds' to avoid conflicts with other Greenhouse mods.

### CODE REVIEW

**Comment by SpoonyBoobah** [comment]
Hope this change from Plant to Seeds is OK, sorry if this is a pain. Noticed that many mods that have a greenhouse usualy also have a science experiment called 'Observe Plant Growth' so thought it would be better to change the name to make it distinct from them.

**Comment by linuxgurugamer** [comment]
Thanks, but I'd like some changes.

Your changes now refer to both plants and seeds interchangeably.  You also use "Seedlings"

How about making them all consistent and use "seedlings" for all of these descriptions?

**Comment by SpoonyBoobah** [comment]
Hi linuxgurugamer,

Thanks for your quick feedback, it is much appreciated. The reason I did that was to give variety to the science reports due to plant's life cycle of - Seed > Seedling > Plant/Tree > Seed/Fruit. So the effects of the biome could have different effects to the seeds at different stages of their development.

Also, some of the reports like JoolInSpace are very generalised so using 'Plants' is more appropriate then using the more specific terms of Seeds or Seedlings e.g. "Plants are green. Jool is green. You are green. Are these coincidences? Probably."

So, would you still like me to change them?

**Comment by linuxgurugamer** [comment]
Nope, that's fine.thanks, will merge soon

**Pull request merged**
