### PR TITLE
SystemHeat patch for StationScience

### PR DESCRIPTION
**Pull request by Grimmas**
This adds support for SystemHeat.

Note 1: I increased the heat generation per part from 2kw to 200kw for this patch only (does not affect base mod, although I would suggest this change for the base mod as well). Now you might actually need bigger radiators to cool these parts. 

Note 2: the Spectrometron does not actually generate any core heat despite having the module, so I didn't add anything for it either. Fixing this would require changes to the SampleAnalyzer module or another workaround.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Thanks

**Comment by linuxgurugamer** [comment]
I'd suggest you submit this to the new maintainers of Station Science here:

https://forum.kerbalspaceprogram.com/index.php?/topic/210617-wip-stationscience-v30-renewed/

I'll release this for now, but eventually they will have it in full

**Comment by Grimmas** [comment]
Thanks for the heads up, I did see that thread but they had no repo of their own, their repo link was back to your repo.

**Comment by linuxgurugamer** [comment]
Ok, post a message there so they are aware of it, I've already merged and released it

**Pull request merged**
